In [1]:
# Insatlling world bank data
!pip install wbdata
!pip install wbgapi
!pip install world_bank_data --upgrade

In [2]:
import numpy as np
import pandas as pd
import wbgapi as wb
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

### Choosing random countries of interest

In [3]:
# Choose 30 of random counries around the world
countries = ['Albania', 'Algeria', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 
            'Belarus', 'Belgium', 'Bolivia', 'Brazil', 'British Virgin Islands', 
            'Brunei', 'Bulgaria', 'Cameroon', 'Canada', 'Chad', 'Chile', 'China', 
            'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Falkland Island', 
            'Fiji', 'Israel', 'Italy', 'Japan', 'Kazakhstan', 'Kenya', 'Kiribati']

# Get the country codes into dictionary, Key => country code, Value => Country name
country_codes = {
    'ALB'	: 'Albania',
    'DZA'	: 'Algeria',
    'BHS'	: 'Bahamas, The',
    'BHR'	: 'Bahrain',
    'BGD'	: 'Bangladesh',
    'BRB'	: 'Barbados',
    'BLR'	: 'Belarus',
    'BEL'	: 'Belgium',
    'BOL'	: 'Bolivia',
    'BRA'	: 'Brazil',
    'VGB'	: 'British Virgin Islands',
    'BRN'	: 'Brunei',
    'BGR'	: 'Bulgaria',
    'CMR'	: 'Cameroon',
    'CAN'	: 'Canada',
    'TCD'	: 'Chad',
    'CHL'	: 'Chile',
    'CHN'	: 'China',
    'DNK'	: 'Denmark',
    'DJI'	: 'Djibouti',
    'DMA'	: 'Dominica',
    'DOM'	: 'Dominican Republic',
    'FLK'	: 'Falkland Island',
    'FJI'	: 'Fiji',
    'ISR'	: 'Israel',
    'ITA'	: 'Italy',
    'JPN'	: 'Japan',
    'KAZ'	: 'Kazakhstan',
    'KEN'	: 'Kenya',
    'KIR'	: 'Kiribati'
}

Setting the indicator of intrest.

In [4]:
indicator = 'SP.DYN.LE00.FE.IN'

# Check indicator name
wb.series.info(indicator)

id                 value
-----------------  ----------------------------------------
SP.DYN.LE00.FE.IN  Life expectancy at birth, female (years)
                   1 elements

In [5]:
# Loading the data
data = wb.data.DataFrame(indicator, country_codes, mrv=20, labels = True).set_index('Country')
data

,YR2001,YR2002,YR2003,YR2004,YR2005,YR2006,YR2007,YR2008,YR2009,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
Country,,,,,,,,,,,,,,,,,,,,
Kiribati,66.309,66.656,67.001,67.345,67.696,68.061,68.442,68.838,69.245,69.654,70.052,70.429,70.777,71.094,71.379,71.638,71.880,72.113,72.342,72.568
Kenya,53.434,53.837,54.535,55.497,56.667,57.969,59.315,60.624,61.844,62.944,63.923,64.815,65.647,66.415,67.111,67.721,68.244,68.684,69.049,69.352
Kazakhstan,71.300,71.600,71.500,72.000,71.800,72.000,72.300,72.400,73.250,73.410,73.570,74.290,75.230,75.820,76.260,76.610,76.920,77.190,77.300,75.530
Japan,84.900,85.200,85.330,85.590,85.490,85.810,85.990,86.050,86.440,86.300,85.900,86.410,86.610,86.830,86.990,87.140,87.260,87.320,87.450,87.740
Italy,83.200,83.200,82.800,83.700,83.600,84.100,84.200,84.200,84.300,84.700,84.800,84.800,85.200,85.600,84.900,85.600,85.200,85.600,85.700,84.700
Israel,81.200,81.500,81.800,82.400,82.200,82.500,82.400,83.000,83.300,83.600,83.500,83.600,83.900,84.100,84.100,84.200,84.600,84.800,84.700,84.800
Fiji,67.616,67.736,67.830,67.895,67.938,67.972,68.013,68.073,68.157,68.262,68.378,68.496,68.609,68.715,68.818,68.925,69.043,69.178,69.331,69.498
Dominican Republic,72.779,73.076,73.372,73.664,73.951,74.229,74.499,74.761,75.015,75.264,75.513,75.764,76.018,76.273,76.525,76.765,76.990,77.196,77.381,77.549
Dominica,NaN,78.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Djibouti,58.653,58.751,58.914,59.149,59.449,59.800,60.189,60.611,61.074,61.611,62.269,63.066,63.994,65.021,66.086,67.109,68.023,68.778,69.357,69.766
Denmark,79.200,79.200,79.500,79.900,80.200,80.400,80.500,80.700,80.800,81.200,81.900,82.100,82.400,82.800,82.700,82.800,83.100,82.900,83.500,83.600
China,73.674,73.951,74.237,74.535,74.845,75.170,75.508,75.855,76.208,76.566,76.926,77.284,77.635,77.972,78.288,78.574,78.828,79.051,79.244,79.411
Chile,79.628,79.881,80.123,80.355,80.579,80.800,81.021,81.242,81.458,81.661,81.841,81.990,82.106,82.191,82.250,82.293,82.333,82.381,82.442,82.522
Chad,48.978,49.086,49.241,49.450,49.731,50.096,50.540,51.049,51.608,52.188,52.759,53.294,53.777,54.196,54.552,54.856,55.132,55.400,55.669,55.945
Canada,81.900,82.000,82.200,82.300,82.600,82.700,82.900,83.000,83.300,83.500,83.600,83.800,83.900,83.900,84.000,84.000,84.000,84.200,84.200,83.900
Cameroon,52.676,52.894,53.174,53.508,53.889,54.313,54.777,55.271,55.786,56.312,56.844,57.377,57.904,58.418,58.908,59.367,59.795,60.192,60.561,60.904
Bulgaria,75.200,75.400,75.600,76.200,76.300,76.300,76.300,76.600,77.100,77.200,77.800,77.900,78.600,78.000,78.200,78.500,78.400,78.600,78.800,77.500
Brunei Darussalam,74.332,74.525,74.715,74.901,75.082,75.257,75.425,75.586,75.738,75.883,76.022,76.156,76.286,76.416,76.547,76.681,76.819,76.960,77.106,77.256
British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brazil,74.360,74.715,75.069,75.423,75.775,76.122,76.457,76.779,77.085,77.378,77.658,77.929,78.193,78.450,78.698,78.934,79.156,79.362,79.555,79.736
Bolivia,65.054,65.695,66.321,66.934,67.538,68.137,68.736,69.334,69.930,70.518,71.091,71.643,72.166,72.655,73.105,73.512,73.878,74.209,74.508,74.780
Belgium,81.200,81.200,81.100,81.900,81.900,82.300,82.600,82.600,82.800,83.000,83.300,83.100,83.200,83.900,83.400,84.000,83.900,83.900,84.300,83.100
Belarus,74.500,74.100,74.700,75.000,75.100,75.500,76.200,76.500,76.400,76.500,76.700,77.600,77.900,78.400,78.900,79.000,79.200,79.400,79.400,79.400
Barbados,79.093,79.222,79.332,79.425,79.504,79.573,79.636,79.695,79.755,79.816,79.880,79.945,80.012,80.080,80.152,80.227,80.307,80.392,80.482,80.579
Bangladesh,66.574,67.126,67.661,68.189,68.715,69.240,69.761,70.272,70.773,71.257,71.721,72.159,72.571,72.955,73.316,73.655,73.978,74.291,74.595,74.893
Bahrain,75.601,75.771,75.942,76.112,76.282,76.450,76.615,76.776,76.933,77.087,77.240,77.392,77.544,77.696,77.848,77.997,78.143,78.285,78.423,78.557
"Bahamas, The",75.101,75.025,74.942,74.859,74.782,74.715,74.659,74.619,74.600,74.614,74.670,74.771,74.914,75.093,75.296,75.509,75.718,75.911,76.081,76.228
Algeria,72.542,73.015,73.491,73.959,74.409,74.829,75.215,75.563,75.875,76.152,76.403,76.637,76.863,77.085,77.306,77.524,77.735,77.938,78.133,78.321
Albania,77.263,77.538,77.777,77.982,78.165,78.349,78.551,78.781,79.037,79.302,79.554,79.770,79.934,80.045,80.107,80.134,80.148,80.167,80.201,80.256